/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author abrilislas
 */
public class JFrame_MenuPrincipal extends JFrame_Padre {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName());

    /**
     * Creates new form JFrame_MenuPrincipal
     */
    public JFrame_MenuPrincipal() {
        super();
        initComponents();
        setTitle("Grafo Michoacán | Menú de opciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        headerMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        BotonMenu_Recorridos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonMenu_AEM = new javax.swing.JButton();
        BotonMenu_VisualizarGrafo = new javax.swing.JButton();
        BotonMenu_RutaCorta = new javax.swing.JButton();
        BotonMenu_ComplejidadTemp = new javax.swing.JButton();
        BotonMenu_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(235, 233, 227));
        panelFondo.setLayout(new java.awt.BorderLayout());

        headerMenu.setBackground(new java.awt.Color(0, 51, 51));
        headerMenu.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 153));
        jLabel1.setText("GRAFO DE MICHOACÁN. ");

        javax.swing.GroupLayout headerMenuLayout = new javax.swing.GroupLayout(headerMenu);
        headerMenu.setLayout(headerMenuLayout);
        headerMenuLayout.setHorizontalGroup(
            headerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerMenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        headerMenuLayout.setVerticalGroup(
            headerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerMenuLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        panelFondo.add(headerMenu, java.awt.BorderLayout.PAGE_START);

        panelBotones.setBackground(new java.awt.Color(248, 242, 232));

        BotonMenu_Recorridos.setBackground(new java.awt.Color(240, 228, 208));
        BotonMenu_Recorridos.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonMenu_Recorridos.setForeground(new java.awt.Color(51, 51, 0));
        BotonMenu_Recorridos.setText("Recorridos");
        BotonMenu_Recorridos.setBorderPainted(false);
        BotonMenu_Recorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenu_RecorridosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Menú de opciones");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Selecciona una opción...");

        BotonMenu_AEM.setBackground(new java.awt.Color(240, 228, 208));
        BotonMenu_AEM.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonMenu_AEM.setForeground(new java.awt.Color(51, 51, 0));
        BotonMenu_AEM.setText("Árbol de expansión mínima");
        BotonMenu_AEM.setBorderPainted(false);
        BotonMenu_AEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenu_AEMActionPerformed(evt);
            }
        });

        BotonMenu_VisualizarGrafo.setBackground(new java.awt.Color(240, 228, 208));
        BotonMenu_VisualizarGrafo.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonMenu_VisualizarGrafo.setForeground(new java.awt.Color(51, 51, 0));
        BotonMenu_VisualizarGrafo.setText("Visualización de grafos");
        BotonMenu_VisualizarGrafo.setBorderPainted(false);
        BotonMenu_VisualizarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenu_VisualizarGrafoActionPerformed(evt);
            }
        });

        BotonMenu_RutaCorta.setBackground(new java.awt.Color(240, 228, 208));
        BotonMenu_RutaCorta.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonMenu_RutaCorta.setForeground(new java.awt.Color(51, 51, 0));
        BotonMenu_RutaCorta.setText("Rutas más cortas");
        BotonMenu_RutaCorta.setBorderPainted(false);
        BotonMenu_RutaCorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenu_RutaCortaActionPerformed(evt);
            }
        });

        BotonMenu_ComplejidadTemp.setBackground(new java.awt.Color(240, 228, 208));
        BotonMenu_ComplejidadTemp.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonMenu_ComplejidadTemp.setForeground(new java.awt.Color(51, 51, 0));
        BotonMenu_ComplejidadTemp.setText("Complejidad Temporal");
        BotonMenu_ComplejidadTemp.setBorderPainted(false);
        BotonMenu_ComplejidadTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenu_ComplejidadTempActionPerformed(evt);
            }
        });

        BotonMenu_Salir.setBackground(new java.awt.Color(204, 255, 204));
        BotonMenu_Salir.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonMenu_Salir.setForeground(new java.awt.Color(0, 51, 51));
        BotonMenu_Salir.setText("Salir");
        BotonMenu_Salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 1, true));
        BotonMenu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenu_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonMenu_VisualizarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonMenu_RutaCorta, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBotonesLayout.createSequentialGroup()
                                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonMenu_Recorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonMenu_AEM, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonMenu_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonMenu_ComplejidadTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(BotonMenu_VisualizarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMenu_Recorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMenu_ComplejidadTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMenu_AEM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMenu_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(BotonMenu_RutaCorta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        panelFondo.add(panelBotones, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMenu_RecorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenu_RecorridosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenu_RecorridosActionPerformed

    private void BotonMenu_AEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenu_AEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenu_AEMActionPerformed

    private void BotonMenu_VisualizarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenu_VisualizarGrafoActionPerformed
        new JFrame_VisualizarGrafo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonMenu_VisualizarGrafoActionPerformed

    private void BotonMenu_RutaCortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenu_RutaCortaActionPerformed
        new JFrame_RutaMasCorta().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonMenu_RutaCortaActionPerformed

    private void BotonMenu_ComplejidadTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenu_ComplejidadTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenu_ComplejidadTempActionPerformed

    private void BotonMenu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenu_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonMenu_SalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu_AEM;
    private javax.swing.JButton BotonMenu_ComplejidadTemp;
    private javax.swing.JButton BotonMenu_Recorridos;
    private javax.swing.JButton BotonMenu_RutaCorta;
    private javax.swing.JButton BotonMenu_Salir;
    private javax.swing.JButton BotonMenu_VisualizarGrafo;
    private javax.swing.JPanel headerMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
