/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author abrilislas
 */
public class JFrame_OpcionesTimeComplexity extends JFrame_Padre {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_OpcionesTimeComplexity.class.getName());
    private String MEJOR_CASO;
    private String PEOR_CASO;
    private String CASO_PROMEDIO;
    /**
     * Creates new form JFrame_MenuPrincipal
     */
    public JFrame_OpcionesTimeComplexity() {
        super();
        initComponents();
        setTitle("Grafo Michoacán | Menú de opciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        headerMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonTC_Dijkstra = new javax.swing.JButton();
        BotonTC_DFS = new javax.swing.JButton();
        BotonTC_Kruskal = new javax.swing.JButton();

        panelFondo.setBackground(new java.awt.Color(235, 233, 227));
        panelFondo.setLayout(new java.awt.BorderLayout());

        headerMenu.setBackground(new java.awt.Color(0, 51, 51));
        headerMenu.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 153));
        jLabel1.setText("Complejidad temporal");

        javax.swing.GroupLayout headerMenuLayout = new javax.swing.GroupLayout(headerMenu);
        headerMenu.setLayout(headerMenuLayout);
        headerMenuLayout.setHorizontalGroup(
            headerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerMenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        headerMenuLayout.setVerticalGroup(
            headerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerMenuLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        panelFondo.add(headerMenu, java.awt.BorderLayout.PAGE_START);

        panelBotones.setBackground(new java.awt.Color(248, 242, 232));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Complejidad temporal de los algoritmos ");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Selecciona un algoritmo...");

        BotonTC_Dijkstra.setBackground(new java.awt.Color(0, 51, 51));
        BotonTC_Dijkstra.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonTC_Dijkstra.setForeground(new java.awt.Color(240, 228, 208));
        BotonTC_Dijkstra.setText("Dijkstra");
        BotonTC_Dijkstra.setBorderPainted(false);
        BotonTC_Dijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTC_DijkstraActionPerformed(evt);
            }
        });

        BotonTC_DFS.setBackground(new java.awt.Color(0, 51, 51));
        BotonTC_DFS.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonTC_DFS.setForeground(new java.awt.Color(240, 228, 208));
        BotonTC_DFS.setText("DFS (Depth-First Search)");
        BotonTC_DFS.setBorderPainted(false);
        BotonTC_DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTC_DFSActionPerformed(evt);
            }
        });

        BotonTC_Kruskal.setBackground(new java.awt.Color(0, 51, 51));
        BotonTC_Kruskal.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        BotonTC_Kruskal.setForeground(new java.awt.Color(240, 228, 208));
        BotonTC_Kruskal.setText("Kruskal");
        BotonTC_Kruskal.setBorderPainted(false);
        BotonTC_Kruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTC_KruskalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonTC_Kruskal, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTC_DFS, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTC_Dijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(398, 398, 398))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(262, 262, 262))))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(BotonTC_DFS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BotonTC_Dijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BotonTC_Kruskal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        panelFondo.add(panelBotones, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTC_DijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTC_DijkstraActionPerformed
        MEJOR_CASO = "Ω(V log V + E)";
        PEOR_CASO = "Θ(E log V)";
        CASO_PROMEDIO = "O(E log V)";
        
        generarReporteDeComplejidad().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonTC_DijkstraActionPerformed

    private void BotonTC_DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTC_DFSActionPerformed
        MEJOR_CASO = "Ω(V + E)";
        PEOR_CASO = "Θ(V + E)";
        CASO_PROMEDIO = "O(V+E)";
        
        generarReporteDeComplejidad().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonTC_DFSActionPerformed

    private void BotonTC_KruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTC_KruskalActionPerformed

        MEJOR_CASO = "Ω(E log V)";
        PEOR_CASO = "Θ(E log V)";
        CASO_PROMEDIO = "O(E log V)";        MEJOR_CASO = "Ω(E log V)";
        PEOR_CASO = "Θ(E log V)";
        CASO_PROMEDIO = "O(E log V)";
        
        generarReporteDeComplejidad().setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonTC_KruskalActionPerformed
    
    private JFrame_TimeComplexity generarReporteDeComplejidad(){
        JFrame_TimeComplexity frameComplejidad = new JFrame_TimeComplexity(MEJOR_CASO,PEOR_CASO,CASO_PROMEDIO);
        return frameComplejidad;
    
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonTC_DFS;
    private javax.swing.JButton BotonTC_Dijkstra;
    private javax.swing.JButton BotonTC_Kruskal;
    private javax.swing.JPanel headerMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
